/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyecto.Comida;

/**
 *
 * @author jorge
 */
public class Menu_1 extends javax.swing.JPanel {

    ArrayList<Comida> lista = new ArrayList<>();
    Pedidos pedidos = new Pedidos();
    double sum;

    /**
     * Creates new form Menu
     */
    public Menu_1() {
        
        initComponents();
        actualizarMenu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        DefaultTableModel modelo = new DefaultTableModel(
            new String[]{"Nombre", "Precio", ""}, 0
        );

        for (Comida comida : lista) {
            Object[] fila = new Object[]{
                comida.getNombre(),
                comida.getPrecio(),
                "Agregar"
            };
            modelo.addRow(fila);
        }
        comTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        pedTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        totLabel = new javax.swing.JLabel();
        btnPedido = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        comTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][][] {},
            new String[] {
                "Nombre", "Precio", "Añadir"
            }
        ));
        comTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(comTable);

        pedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][][] {},
            new String[] {
                "Nombre", "Precio", ""
            }
        ));
        pedTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pedTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(pedTable);

        jLabel1.setText("Total:");

        btnPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPedidoMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("DejaVu Serif Condensed", 0, 15)); // NOI18N
        jLabel2.setText("Hacer Pedido");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnPedidoLayout = new javax.swing.GroupLayout(btnPedido);
        btnPedido.setLayout(btnPedidoLayout);
        btnPedidoLayout.setHorizontalGroup(
            btnPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPedidoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        btnPedidoLayout.setVerticalGroup(
            btnPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(totLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comTableMouseClicked
        int fila = comTable.rowAtPoint(evt.getPoint());
        int columna = comTable.columnAtPoint(evt.getPoint());

        if (columna == 2) {
            String nombre = (String) comTable.getValueAt(fila, 0);
            Double precio = (Double) comTable.getValueAt(fila, 1);
            pedidos.agregar(nombre, precio);
            agregar(nombre, precio);
             sum=pedidos.sum();
            totLabel.setText(String.valueOf(sum));
        }
    }//GEN-LAST:event_comTableMouseClicked

    private void pedTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pedTableMouseClicked
        int fila = pedTable.rowAtPoint(evt.getPoint());
        int columna = pedTable.columnAtPoint(evt.getPoint());
        if (columna == 2) {
            String comida = (String) pedTable.getValueAt(fila, 0);
            pedidos.eliminar(comida);
            DefaultTableModel modelo = (DefaultTableModel) pedTable.getModel();
            modelo.removeRow(fila);
             sum=pedidos.res();
             
            totLabel.setText(String.valueOf(sum));
        }
    }//GEN-LAST:event_pedTableMouseClicked

    private void btnPedidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPedidoMousePressed
      
    }//GEN-LAST:event_btnPedidoMousePressed

    public void agregar(String nombre, Double precio) {
        DefaultTableModel modelo = (DefaultTableModel) pedTable.getModel();
        modelo.addRow(new Object[]{nombre, precio, "Eliminar"});
    }
    private void actualizarMenu() {
    DefaultTableModel model = (DefaultTableModel) comTable.getModel();
    model.setRowCount(0); // Limpia la tabla

    for (Comida comida : ListaUsers.comidaList) {
        Object[] fila = {
            
            comida.nombre,
            comida.precio,
            "Añadir",
            
        };
        model.addRow(fila);
    }

    
    if (ListaUsers.comidaList.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No hay comidas registradas todavía.");
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnPedido;
    private javax.swing.JTable comTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable pedTable;
    private javax.swing.JLabel totLabel;
    // End of variables declaration//GEN-END:variables
}
