/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import proyecto.Comida;
import proyecto.ListaUsers;
import static proyecto.ListaUsers.UsuariosLista;

/**
 *
 * @author jorge
 */
public class Menu_1 extends javax.swing.JPanel {

    ArrayList<Comida> lista = new ArrayList<>();
    Pedidos pedidos = new Pedidos();
    double sum;

    /**
     * Creates new form Menu
     */
    public Menu_1() {
        
        initComponents();
        actualizarMenu();
        lbllogito.setIcon(new ImageIcon(getClass().getResource("/Imagenes/Logito.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogTicket = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtTicket = new javax.swing.JTextArea();
        DialogPedidosConsul = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        TickePed1 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        TickePed2 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        TickePed3 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        TickePed4 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        TickePed5 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        TickePed6 = new javax.swing.JTextArea();
        btnCerrarP = new javax.swing.JLabel();
        btnVaciar = new javax.swing.JButton();
        lbllogito = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DefaultTableModel modelo = new DefaultTableModel(
            new String[]{"Nombre", "Precio", ""}, 0
        );

        for (Comida comida : lista) {
            Object[] fila = new Object[]{
                comida.getNombre(),
                comida.getPrecio(),
                "Agregar"
            };
            modelo.addRow(fila);
        }
        comTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        pedTable = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        totLabel = new javax.swing.JLabel();
        btnPedido = new javax.swing.JPanel();
        lblbtnPedido = new javax.swing.JLabel();
        btnPedidoss = new javax.swing.JPanel();
        lblPedidoss = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JPanel();
        Atrasbtn = new javax.swing.JLabel();

        DialogTicket.setResizable(false);

        txtTicket.setColumns(20);
        txtTicket.setRows(5);
        jScrollPane3.setViewportView(txtTicket);

        javax.swing.GroupLayout DialogTicketLayout = new javax.swing.GroupLayout(DialogTicket.getContentPane());
        DialogTicket.getContentPane().setLayout(DialogTicketLayout);
        DialogTicketLayout.setHorizontalGroup(
            DialogTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogTicketLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        DialogTicketLayout.setVerticalGroup(
            DialogTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogTicketLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        DialogPedidosConsul.setResizable(false);

        TickePed1.setColumns(20);
        TickePed1.setRows(5);
        jScrollPane4.setViewportView(TickePed1);

        TickePed2.setColumns(20);
        TickePed2.setRows(5);
        jScrollPane5.setViewportView(TickePed2);

        TickePed3.setColumns(20);
        TickePed3.setRows(5);
        jScrollPane6.setViewportView(TickePed3);

        TickePed4.setColumns(20);
        TickePed4.setRows(5);
        jScrollPane7.setViewportView(TickePed4);

        TickePed5.setColumns(20);
        TickePed5.setRows(5);
        jScrollPane8.setViewportView(TickePed5);

        TickePed6.setColumns(20);
        TickePed6.setRows(5);
        jScrollPane9.setViewportView(TickePed6);

        btnCerrarP.setText("CERRAR");
        btnCerrarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCerrarPMousePressed(evt);
            }
        });

        btnVaciar.setText("Vaciar");
        btnVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DialogPedidosConsulLayout = new javax.swing.GroupLayout(DialogPedidosConsul.getContentPane());
        DialogPedidosConsul.getContentPane().setLayout(DialogPedidosConsulLayout);
        DialogPedidosConsulLayout.setHorizontalGroup(
            DialogPedidosConsulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogPedidosConsulLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(DialogPedidosConsulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCerrarP, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVaciar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DialogPedidosConsulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(DialogPedidosConsulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(DialogPedidosConsulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(DialogPedidosConsulLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );
        DialogPedidosConsulLayout.setVerticalGroup(
            DialogPedidosConsulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogPedidosConsulLayout.createSequentialGroup()
                .addGroup(DialogPedidosConsulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DialogPedidosConsulLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(DialogPedidosConsulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(jScrollPane5)
                            .addComponent(jScrollPane6)))
                    .addGroup(DialogPedidosConsulLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(btnCerrarP, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(DialogPedidosConsulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DialogPedidosConsulLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DialogPedidosConsulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(jScrollPane9)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogPedidosConsulLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVaciar)
                        .addGap(142, 142, 142))))
        );

        setBackground(new java.awt.Color(255, 204, 51));

        comTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][][] {},
            new String[] {
                "Nombre", "Precio", "Añadir"
            }
        ));
        comTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(comTable);

        pedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][][] {},
            new String[] {
                "Nombre", "Precio", ""
            }
        ));
        pedTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pedTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(pedTable);

        lblTotal.setText("Total:");

        btnPedido.setBackground(new java.awt.Color(255, 204, 51));
        btnPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPedidoMousePressed(evt);
            }
        });

        lblbtnPedido.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        lblbtnPedido.setText("  Hacer Pedido");
        lblbtnPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblbtnPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblbtnPedidoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblbtnPedidoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblbtnPedidoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnPedidoLayout = new javax.swing.GroupLayout(btnPedido);
        btnPedido.setLayout(btnPedidoLayout);
        btnPedidoLayout.setHorizontalGroup(
            btnPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblbtnPedido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
        );
        btnPedidoLayout.setVerticalGroup(
            btnPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblbtnPedido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
        );

        btnPedidoss.setBackground(new java.awt.Color(255, 204, 51));

        lblPedidoss.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 15)); // NOI18N
        lblPedidoss.setText("      Pedidos");
        lblPedidoss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblPedidossMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblPedidossMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblPedidossMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnPedidossLayout = new javax.swing.GroupLayout(btnPedidoss);
        btnPedidoss.setLayout(btnPedidossLayout);
        btnPedidossLayout.setHorizontalGroup(
            btnPedidossLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPedidoss, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
        );
        btnPedidossLayout.setVerticalGroup(
            btnPedidossLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPedidoss, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        btnCerrar.setBackground(new java.awt.Color(255, 204, 51));

        Atrasbtn.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 15)); // NOI18N
        Atrasbtn.setText("  Cerrar Sesion");
        Atrasbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AtrasbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AtrasbtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AtrasbtnMousePressed(evt);
            }
        });

        javax.swing.GroupLayout btnCerrarLayout = new javax.swing.GroupLayout(btnCerrar);
        btnCerrar.setLayout(btnCerrarLayout);
        btnCerrarLayout.setHorizontalGroup(
            btnCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Atrasbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        );
        btnCerrarLayout.setVerticalGroup(
            btnCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Atrasbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPedidoss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbllogito, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(btnPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(totLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                .addComponent(totLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbllogito, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPedidoss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    //Evento que realiza cuando se clickea
    private void comTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comTableMouseClicked
        int fila = comTable.rowAtPoint(evt.getPoint());
        int columna = comTable.columnAtPoint(evt.getPoint());

        if (columna == 2) {
            String nombre = (String) comTable.getValueAt(fila, 0);
            Double precio = (Double) comTable.getValueAt(fila, 1);
            pedidos.agregar(nombre, precio);
            agregar(nombre, precio);
             sum=pedidos.sum();
            totLabel.setText(String.valueOf(sum));
        }
    }//GEN-LAST:event_comTableMouseClicked
    //Evento que realiza cuando se clickea
    private void pedTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pedTableMouseClicked
        int fila = pedTable.rowAtPoint(evt.getPoint());
        int columna = pedTable.columnAtPoint(evt.getPoint());
        if (columna == 2) {
            String comida = (String) pedTable.getValueAt(fila, 0);
            pedidos.eliminar(comida);
            DefaultTableModel modelo = (DefaultTableModel) pedTable.getModel();
            modelo.removeRow(fila);
             sum=pedidos.res();
             
            totLabel.setText(String.valueOf(sum));
        }
    }//GEN-LAST:event_pedTableMouseClicked

    private void btnPedidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPedidoMousePressed
      
    }//GEN-LAST:event_btnPedidoMousePressed
    //Evento que realiza cuando se presiona
    private void AtrasbtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AtrasbtnMousePressed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frame.getContentPane().removeAll();
        frame.dispose(); // Cierra el actual
        new login().setVisible(true);
       
    }//GEN-LAST:event_AtrasbtnMousePressed
    //Evento que realiza cuando se presiona
    private void btnCerrarPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarPMousePressed
      DialogPedidosConsul.setVisible(false);
    }//GEN-LAST:event_btnCerrarPMousePressed
    //Cuando el boton vaciar los pedidos se borran
    private void btnVaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciarActionPerformed
         TickePed1.setText("");
         TickePed2.setText("");
         TickePed3.setText("");
         TickePed4.setText("");
         TickePed5.setText("");
         TickePed6.setText("");
    }//GEN-LAST:event_btnVaciarActionPerformed
    // los evt de entered o exited es para diseño de el boton cuando el cursor pasa encima o sale de el
    private void AtrasbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AtrasbtnMouseEntered
        btnCerrar.setBackground(Color.red);
    }//GEN-LAST:event_AtrasbtnMouseEntered

    private void AtrasbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AtrasbtnMouseExited
        btnCerrar.setBackground(new Color(255,204,51));
    }//GEN-LAST:event_AtrasbtnMouseExited

    private void lblPedidossMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPedidossMouseEntered
         btnPedidoss.setBackground(new Color(255,153,51));
    }//GEN-LAST:event_lblPedidossMouseEntered

    private void lblPedidossMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPedidossMouseExited
        btnPedidoss.setBackground(new Color(255,204,51));
    }//GEN-LAST:event_lblPedidossMouseExited

    private void lblPedidossMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPedidossMousePressed
       DialogPedidosConsul.setBounds(0,0,891,590);
        DialogPedidosConsul.setVisible(true);
    }//GEN-LAST:event_lblPedidossMousePressed

    private void lblbtnPedidoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbtnPedidoMouseEntered
        lblbtnPedido.setBackground(new Color(255,153,51));
    }//GEN-LAST:event_lblbtnPedidoMouseEntered

    private void lblbtnPedidoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbtnPedidoMouseExited
        lblbtnPedido.setBackground(new Color(255,204,51));
    }//GEN-LAST:event_lblbtnPedidoMouseExited
    //Evento que realiza cuando se presiona
    private void lblbtnPedidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbtnPedidoMousePressed
          DialogTicket.setBounds(0,0,371,460);
        DialogTicket.setVisible(true);
        txtTicket.setText(Ticket(pedTable));
        if (TickePed1.getText().isEmpty()) {
        TickePed1.setText(Ticket(pedTable));
    } else if (TickePed2.getText().isEmpty()) {
        TickePed2.setText(Ticket(pedTable));
    } else if (TickePed3.getText().isEmpty()) {
        TickePed3.setText(Ticket(pedTable));
    } else if (TickePed4.getText().isEmpty()) {
        TickePed4.setText(Ticket(pedTable));
    } else if (TickePed5.getText().isEmpty()) {
        TickePed5.setText(Ticket(pedTable));
    } else if(TickePed6.getText().isEmpty()) {
        TickePed6.setText(Ticket(pedTable));
    }else{
        JOptionPane.showMessageDialog(this, "No hay espacio para más tickets.");
    }


     DefaultTableModel model = (DefaultTableModel) pedTable.getModel();
        model.setRowCount(0); // Esto borra todas las filas de la tabla
    }//GEN-LAST:event_lblbtnPedidoMousePressed

    public void agregar(String nombre, Double precio) {
        DefaultTableModel modelo = (DefaultTableModel) pedTable.getModel();
        modelo.addRow(new Object[]{nombre, precio, "Eliminar"});
    }
    //Actualiza el menu que se mostrara al cliente
    private void actualizarMenu() {
    DefaultTableModel model = (DefaultTableModel) comTable.getModel();
    model.setRowCount(0); // Limpia la tabla

    for (Comida comida : ListaUsers.comidaList) {
        Object[] fila = {
            
            comida.nombre,
            comida.precio,
            "Añadir",
            
        };
        model.addRow(fila);
    }

    
    if (ListaUsers.comidaList.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No hay comidas registradas todavía.");
    }
}
    
    
    public String Ticket(JTable pedTable) {
    StringBuilder ticket = new StringBuilder();
    double total = 0.0;

    ticket.append("=== TICKET DE COMPRA ===\n\n");

    DefaultTableModel model = (DefaultTableModel) pedTable.getModel();

    // Listas para productos únicos
    ArrayList<String> productos = new ArrayList<>();
    ArrayList<Integer> cantidades = new ArrayList<>();
    ArrayList<Double> subtotales = new ArrayList<>();

    for (int i = 0; i < model.getRowCount(); i++) {
        String producto = model.getValueAt(i, 0).toString();
        double precio = Double.parseDouble(model.getValueAt(i, 1).toString());

        if (productos.contains(producto)) {
            int index = productos.indexOf(producto);
            cantidades.set(index, cantidades.get(index) + 1);
            subtotales.set(index, subtotales.get(index) + precio);
        } else {
            productos.add(producto);
            cantidades.add(1);
            subtotales.add(precio);
        }
    }

    // Mostrar los productos agrupados
    for (int i = 0; i < productos.size(); i++) {
        String producto = productos.get(i);
        int cantidad = cantidades.get(i);
        double subtotal = subtotales.get(i);

        ticket.append(String.format("%-15s x%-2d $%.2f\n", producto, cantidad, subtotal));
        total += subtotal;
    }

    ticket.append("\n------------------------\n");
    ticket.append(String.format("TOTAL:          $%.2f\n", total));
    ticket.append("========================\n");

    return ticket.toString();
}

//    public String Ticket(JTable pedTable)  {
//    StringBuilder ticket = new StringBuilder();
//    double total = 0.0;
//
//    
//    
//    ticket.append("=== TICKET DE COMPRA ===\n");
//    
//
//    DefaultTableModel model = (DefaultTableModel) pedTable.getModel();
//
//    for (int i = 0; i < model.getRowCount(); i++) {
//        String producto = model.getValueAt(i, 0).toString();
//        double precio = Double.parseDouble(model.getValueAt(i, 1).toString());
//
//        ticket.append(String.format("%-20s $%.2f\n", producto, precio));
//        total += precio;
//    }
//
//    ticket.append("\n------------------------\n");
//    ticket.append(String.format("TOTAL:          $%.2f\n", total));
//    ticket.append("========================\n");
//    
//   return ticket.toString();
//}

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Atrasbtn;
    private javax.swing.JDialog DialogPedidosConsul;
    private javax.swing.JDialog DialogTicket;
    private javax.swing.JTextArea TickePed1;
    private javax.swing.JTextArea TickePed2;
    private javax.swing.JTextArea TickePed3;
    private javax.swing.JTextArea TickePed4;
    private javax.swing.JTextArea TickePed5;
    private javax.swing.JTextArea TickePed6;
    private javax.swing.JPanel btnCerrar;
    private javax.swing.JLabel btnCerrarP;
    private javax.swing.JPanel btnPedido;
    private javax.swing.JPanel btnPedidoss;
    private javax.swing.JButton btnVaciar;
    private javax.swing.JTable comTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lblPedidoss;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblbtnPedido;
    private javax.swing.JLabel lbllogito;
    private javax.swing.JTable pedTable;
    private javax.swing.JLabel totLabel;
    private javax.swing.JTextArea txtTicket;
    // End of variables declaration//GEN-END:variables
}
