/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto;

import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static proyecto.ListaUsers.*;

/**
 *
 * @author manugr
 */
public class PanelAdmin extends javax.swing.JPanel {
    
    //Atributos
    int i,j;
    login l=new login();
    
    //Metodos
    
    
    
    
    
    public PanelAdmin() {
        initComponents();
        LOGO.setIcon(new ImageIcon(getClass().getResource("/Imagenes/LOGO2.png")));
        usuariosSub1.setVisible(false);
        usuariosSub.setVisible(false);
        contEdit.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LOGO = new javax.swing.JLabel();
        Registro = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        contra = new javax.swing.JTextField();
        registrarbuttom = new javax.swing.JButton();
        Edicion = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        person = new javax.swing.JTextField();
        contEdit = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        editNombre = new javax.swing.JTextField();
        editUser = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        editContra = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        Comidas = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        label3 = new javax.swing.JLabel();
        spinPrecio = new javax.swing.JSpinner();
        label4 = new javax.swing.JLabel();
        boxTipo = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        textID = new javax.swing.JSpinner();
        comidaEdit = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        bnombre = new javax.swing.JTextField();
        buscarbtn = new javax.swing.JButton();
        buscarcont = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        nuevoID = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        nuevoNombre = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        nuevoPrecio = new javax.swing.JSpinner();
        nuevoTipo = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        btnEditComida = new javax.swing.JButton();
        ContendorMenus = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        labelComida = new javax.swing.JLabel();
        usuariosSub = new javax.swing.JPanel();
        btRegistro = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JLabel();
        exitU = new javax.swing.JButton();
        btnEditar = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        usuariosSub1 = new javax.swing.JPanel();
        btRegistro1 = new javax.swing.JLabel();
        btnEliminar1 = new javax.swing.JLabel();
        exitU1 = new javax.swing.JButton();
        btnEditar1 = new javax.swing.JLabel();
        btnMostrar1 = new javax.swing.JLabel();

        LOGO.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Registro.setTitle("Registro de Usuarios");
        Registro.setMinimumSize(new java.awt.Dimension(400, 400));
        Registro.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                RegistroWindowClosing(evt);
            }
        });

        jLabel1.setText("Nombre Completo");

        jLabel2.setText("User");

        jLabel3.setText("Contraseña");

        registrarbuttom.setText("Registrar");
        registrarbuttom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarbuttomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegistroLayout = new javax.swing.GroupLayout(Registro.getContentPane());
        Registro.getContentPane().setLayout(RegistroLayout);
        RegistroLayout.setHorizontalGroup(
            RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistroLayout.createSequentialGroup()
                        .addGroup(RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registrarbuttom)
                            .addComponent(jLabel1)
                            .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(contra, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(RegistroLayout.createSequentialGroup()
                        .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 258, Short.MAX_VALUE))))
        );
        RegistroLayout.setVerticalGroup(
            RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(registrarbuttom)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        Edicion.setTitle("Editar Usuario");
        Edicion.setMinimumSize(new java.awt.Dimension(400, 430));
        Edicion.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                EdicionWindowClosing(evt);
            }
        });

        jLabel4.setText("User de persona a editar:");

        jLabel5.setText("Nuevo Nombre Completo");

        jLabel6.setText("Nuevo User");

        jLabel7.setText("Nueva Contraseña");

        btnEdit.setText("Editar");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contEditLayout = new javax.swing.GroupLayout(contEdit);
        contEdit.setLayout(contEditLayout);
        contEditLayout.setHorizontalGroup(
            contEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contEditLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(contEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEdit)
                    .addGroup(contEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editNombre)
                        .addComponent(jLabel7)
                        .addComponent(jLabel6)
                        .addComponent(editUser)
                        .addComponent(editContra)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        contEditLayout.setVerticalGroup(
            contEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contEditLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnEdit)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EdicionLayout = new javax.swing.GroupLayout(Edicion.getContentPane());
        Edicion.getContentPane().setLayout(EdicionLayout);
        EdicionLayout.setHorizontalGroup(
            EdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EdicionLayout.createSequentialGroup()
                .addGroup(EdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EdicionLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(EdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(person))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar))
                    .addGroup(EdicionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(contEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EdicionLayout.setVerticalGroup(
            EdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EdicionLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EdicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(person, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(contEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        Comidas.setTitle("Comidas");
        Comidas.setMinimumSize(new java.awt.Dimension(350, 400));
        Comidas.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                ComidasWindowClosing(evt);
            }
        });

        jLabel8.setText("ID Comida");

        jLabel9.setText("Nombre");

        label3.setText("Precio");

        spinPrecio.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        label4.setText("Tipo");

        boxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comida", "Bebida", "Postre" }));

        btnAgregar.setText("Agregar Alimento");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        textID.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout ComidasLayout = new javax.swing.GroupLayout(Comidas.getContentPane());
        Comidas.getContentPane().setLayout(ComidasLayout);
        ComidasLayout.setHorizontalGroup(
            ComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComidasLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(ComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregar)
                    .addComponent(boxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(label3)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(textID, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(spinPrecio, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(textNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        ComidasLayout.setVerticalGroup(
            ComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComidasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addGap(7, 7, 7)
                .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(label3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spinPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAgregar)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        comidaEdit.setMinimumSize(new java.awt.Dimension(350, 400));
        comidaEdit.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                comidaEditWindowClosing(evt);
            }
        });

        jLabel10.setText("Nombre de Alimento a editar");

        bnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnombreActionPerformed(evt);
            }
        });

        buscarbtn.setText("Buscar");
        buscarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarbtnActionPerformed(evt);
            }
        });

        jLabel11.setText("Nuevo ID");

        nuevoID.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel12.setText("Nuevo Nombre");

        jLabel13.setText("Nuevo Precio");

        nuevoPrecio.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        nuevoTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comida", "Bebida", "Postre" }));
        nuevoTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoTipoActionPerformed(evt);
            }
        });

        jLabel14.setText("Nuevo Tipo");

        btnEditComida.setText("Editar");
        btnEditComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditComidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buscarcontLayout = new javax.swing.GroupLayout(buscarcont);
        buscarcont.setLayout(buscarcontLayout);
        buscarcontLayout.setHorizontalGroup(
            buscarcontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarcontLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(buscarcontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buscarcontLayout.createSequentialGroup()
                        .addGroup(buscarcontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)
                            .addComponent(nuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(buscarcontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(nuevoID, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(buscarcontLayout.createSequentialGroup()
                        .addGroup(buscarcontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(buscarcontLayout.createSequentialGroup()
                                .addComponent(nuevoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditComida))
                            .addComponent(nuevoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 24, Short.MAX_VALUE))))
        );
        buscarcontLayout.setVerticalGroup(
            buscarcontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscarcontLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nuevoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nuevoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(buscarcontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditComida))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout comidaEditLayout = new javax.swing.GroupLayout(comidaEdit.getContentPane());
        comidaEdit.getContentPane().setLayout(comidaEditLayout);
        comidaEditLayout.setHorizontalGroup(
            comidaEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comidaEditLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(comidaEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(comidaEditLayout.createSequentialGroup()
                        .addComponent(bnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(buscarbtn)
                .addContainerGap())
            .addGroup(comidaEditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buscarcont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        comidaEditLayout.setVerticalGroup(
            comidaEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comidaEditLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(comidaEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarcont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(255, 255, 255));

        ContendorMenus.setBackground(new java.awt.Color(255, 255, 255));
        ContendorMenus.setForeground(new java.awt.Color(255, 204, 153));
        ContendorMenus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Cerrar Sesion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        ContendorMenus.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, -1, -1));

        labelComida.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelComida.setText("Alimentos");
        labelComida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelComidaMousePressed(evt);
            }
        });
        ContendorMenus.add(labelComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        btRegistro.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btRegistro.setText("Registrar");
        btRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btRegistroMousePressed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEliminarMousePressed(evt);
            }
        });

        exitU.setFont(new java.awt.Font("Liberation Sans", 0, 10)); // NOI18N
        exitU.setText("Salir");
        exitU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitUActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEditarMousePressed(evt);
            }
        });

        btnMostrar.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btnMostrar.setText("Mostrar");
        btnMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMostrarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout usuariosSubLayout = new javax.swing.GroupLayout(usuariosSub);
        usuariosSub.setLayout(usuariosSubLayout);
        usuariosSubLayout.setHorizontalGroup(
            usuariosSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuariosSubLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usuariosSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usuariosSubLayout.createSequentialGroup()
                        .addComponent(exitU, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(usuariosSubLayout.createSequentialGroup()
                        .addGroup(usuariosSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btRegistro)
                            .addComponent(btnEliminar)
                            .addComponent(btnEditar)
                            .addComponent(btnMostrar))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        usuariosSubLayout.setVerticalGroup(
            usuariosSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usuariosSubLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btRegistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(exitU, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ContendorMenus.add(usuariosSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 80, -1));

        lblUsuario.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        lblUsuario.setText("Usuarios");
        lblUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblUsuarioMousePressed(evt);
            }
        });
        ContendorMenus.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        btRegistro1.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btRegistro1.setText("Registrar");
        btRegistro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btRegistro1MousePressed(evt);
            }
        });

        btnEliminar1.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btnEliminar1.setText("Eliminar");
        btnEliminar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEliminar1MousePressed(evt);
            }
        });

        exitU1.setFont(new java.awt.Font("Liberation Sans", 0, 10)); // NOI18N
        exitU1.setText("Salir");
        exitU1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitU1ActionPerformed(evt);
            }
        });

        btnEditar1.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btnEditar1.setText("Editar");
        btnEditar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEditar1MousePressed(evt);
            }
        });

        btnMostrar1.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        btnMostrar1.setText("Mostrar");
        btnMostrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMostrar1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout usuariosSub1Layout = new javax.swing.GroupLayout(usuariosSub1);
        usuariosSub1.setLayout(usuariosSub1Layout);
        usuariosSub1Layout.setHorizontalGroup(
            usuariosSub1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuariosSub1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usuariosSub1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usuariosSub1Layout.createSequentialGroup()
                        .addComponent(exitU1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(usuariosSub1Layout.createSequentialGroup()
                        .addGroup(usuariosSub1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btRegistro1)
                            .addComponent(btnEliminar1)
                            .addComponent(btnEditar1)
                            .addComponent(btnMostrar1))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        usuariosSub1Layout.setVerticalGroup(
            usuariosSub1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usuariosSub1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btRegistro1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(exitU1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ContendorMenus.add(usuariosSub1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ContendorMenus, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ContendorMenus, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuarioMousePressed
        usuariosSub.setVisible(true);
    }//GEN-LAST:event_lblUsuarioMousePressed

    private void btRegistroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRegistroMousePressed
        Registro.setVisible(true);
    }//GEN-LAST:event_btRegistroMousePressed

    private void btnEliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMousePressed
        i=validarRegistro(JOptionPane.showInputDialog(this,"Ingrese el user que quiere eliminar: "));
        if(i!=-1){
            UsuariosLista.remove(i);
            i=-1;
        }else{
            JOptionPane.showMessageDialog(this, "Usuario no encontrado");
        }
    }//GEN-LAST:event_btnEliminarMousePressed

    private void btnEditarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMousePressed
        Edicion.setVisible(true);
    }//GEN-LAST:event_btnEditarMousePressed

    private void exitUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitUActionPerformed
        usuariosSub.setVisible(false);
        
        
    }//GEN-LAST:event_exitUActionPerformed

    private void btnMostrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarMousePressed

    private void registrarbuttomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarbuttomActionPerformed
        ListaUsers.nuevoUsuario(userName.getText(), user.getText(), contra.getText());
        userName.setText("");
        user.setText("");
        contra.setText("");
        proyecto.login.nuevomodel();
        
    }//GEN-LAST:event_registrarbuttomActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        i=validarRegistro(person.getText());
        if(i!=-1){
            editNombre.setText(UsuariosLista.get(i).NombreCompleto);
            editUser.setText(UsuariosLista.get(i).Usuario);
            editContra.setText(UsuariosLista.get(i).Contraseña);
            contEdit.setVisible(true);
            
        }else{
            JOptionPane.showMessageDialog(this, "Usuario no encontrado");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        UsuariosLista.get(i).NombreCompleto=editNombre.getText();
        UsuariosLista.get(i).Usuario=editUser.getText();
        UsuariosLista.get(i).Contraseña=editContra.getText();
        editNombre.setText("");
        editUser.setText("");
        editContra.setText("");
        person.setText("");
        i=-1;
    }//GEN-LAST:event_btnEditActionPerformed

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        
        //proyecto.login.Plog.setVisible(true);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void EdicionWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_EdicionWindowClosing
        editNombre.setText("");
        editUser.setText("");
        editContra.setText("");
        person.setText("");
        i=-1;
    }//GEN-LAST:event_EdicionWindowClosing

    private void RegistroWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_RegistroWindowClosing
        userName.setText("");
        user.setText("");
        contra.setText("");
        i=-1;
    }//GEN-LAST:event_RegistroWindowClosing

    private void labelComidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelComidaMousePressed
        usuariosSub1.setVisible(true);
    }//GEN-LAST:event_labelComidaMousePressed

    //METODOS MENU COMIDAS
    private void btRegistro1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRegistro1MousePressed
        Comidas.setVisible(true);
    }//GEN-LAST:event_btRegistro1MousePressed

    private void btnEliminar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminar1MousePressed
        j=ListaUsers.validarComida(JOptionPane.showInputDialog(this,"Ingresa el nombre de la comida a eliminar"));
        if(j!=-1){
            ListaUsers.comidaList.remove(j);
            j=-1;
        }else{
            JOptionPane.showMessageDialog(this, "Sin Resultados");
        }
    }//GEN-LAST:event_btnEliminar1MousePressed

    private void exitU1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitU1ActionPerformed
        usuariosSub1.setVisible(false);
    }//GEN-LAST:event_exitU1ActionPerformed

    private void btnEditar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditar1MousePressed
        comidaEdit.setVisible(true);
        buscarcont.setVisible(false);
    }//GEN-LAST:event_btnEditar1MousePressed

    private void btnMostrar1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrar1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrar1MousePressed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        ListaUsers.nuevaComida((int) textID.getValue(),textNombre.getText(),(double) spinPrecio.getValue(),boxTipo.getSelectedItem().toString());
        textID.setValue(0);
        spinPrecio.setValue(0);
        textNombre.setText("");
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void bnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnombreActionPerformed

    private void nuevoTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoTipoActionPerformed

    private void btnEditComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditComidaActionPerformed
        comidaList.get(i).id=(int)nuevoID.getValue();
        comidaList.get(i).nombre=nuevoNombre.getText();
        comidaList.get(i).precio=(double)nuevoPrecio.getValue();
        comidaList.get(i).tipo=nuevoTipo.getSelectedItem().toString();
        bnombre.setText("");
        nuevoID.setValue(0);
        nuevoNombre.setText("");
        nuevoPrecio.setValue(0);
        j=-1;
        
        
    }//GEN-LAST:event_btnEditComidaActionPerformed

    private void buscarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarbtnActionPerformed
        j=validarComida(bnombre.getText());
        if(j!=-1){
            buscarcont.setVisible(true);
            nuevoID.setValue(comidaList.get(j).id);
            nuevoNombre.setText(comidaList.get(j).nombre);
            nuevoPrecio.setValue(comidaList.get(j).precio);
        }else{
            JOptionPane.showMessageDialog(this, "Comida no encontrada");
        }
    }//GEN-LAST:event_buscarbtnActionPerformed

    private void ComidasWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_ComidasWindowClosing
        textID.setValue(0);
        spinPrecio.setValue(0);
        textNombre.setText("");
        j=-1;
    }//GEN-LAST:event_ComidasWindowClosing

    private void comidaEditWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_comidaEditWindowClosing
        bnombre.setText("");
        nuevoID.setValue(0);
        nuevoNombre.setText("");
        nuevoPrecio.setValue(0);
        j=-1;
    }//GEN-LAST:event_comidaEditWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Comidas;
    private javax.swing.JPanel ContendorMenus;
    private javax.swing.JDialog Edicion;
    private javax.swing.JLabel LOGO;
    private javax.swing.JDialog Registro;
    private javax.swing.JTextField bnombre;
    private javax.swing.JComboBox<String> boxTipo;
    private javax.swing.JLabel btRegistro;
    private javax.swing.JLabel btRegistro1;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEditComida;
    private javax.swing.JLabel btnEditar;
    private javax.swing.JLabel btnEditar1;
    private javax.swing.JLabel btnEliminar;
    private javax.swing.JLabel btnEliminar1;
    private javax.swing.JLabel btnMostrar;
    private javax.swing.JLabel btnMostrar1;
    private javax.swing.JButton buscarbtn;
    private javax.swing.JPanel buscarcont;
    private javax.swing.JDialog comidaEdit;
    private javax.swing.JPanel contEdit;
    private javax.swing.JTextField contra;
    private javax.swing.JTextField editContra;
    private javax.swing.JTextField editNombre;
    private javax.swing.JTextField editUser;
    private javax.swing.JButton exitU;
    private javax.swing.JButton exitU1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel labelComida;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JSpinner nuevoID;
    private javax.swing.JTextField nuevoNombre;
    private javax.swing.JSpinner nuevoPrecio;
    private javax.swing.JComboBox<String> nuevoTipo;
    private javax.swing.JTextField person;
    private javax.swing.JButton registrarbuttom;
    private javax.swing.JSpinner spinPrecio;
    private javax.swing.JSpinner textID;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField user;
    private javax.swing.JTextField userName;
    private javax.swing.JPanel usuariosSub;
    private javax.swing.JPanel usuariosSub1;
    // End of variables declaration//GEN-END:variables
}
